'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IP_TV_By_MONSTERMC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property a() As String
            Get
                Return ResourceManager.GetString("a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AL_M3u_IPTV_06_11_2021__4_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AL_M3u_IPTV_06_11_2021__4_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #EXTINF:-1 tvg-ID=&quot;&quot; tvg-name=&quot;------| ALBANIA |------&quot; tvg-logo=&quot;https://cdn.countryflags.com/thumbs/albania/flag-button-round-250.png&quot; group-title=&quot;EU | ALBANIA&quot;,------| ALBANIA |------
        '''http://grcts.velkas.net:2082/Medelectro_603328/ggO8T18n/114667
        '''#EXTINF:-1 tvg-ID=&quot;&quot; tvg-name=&quot;|AL| BIG BROTHER VIP 1 4K&quot; tvg-logo=&quot;&quot; group-title=&quot;EU | ALBANIA&quot;,|AL| BIG BROTHER VIP 1 4K
        '''http://grcts.velkas.net:2082/Medelectro_603328/ggO8T18n/171196
        '''#EXTINF:-1 tvg-ID=&quot;&quot; tvg-name=&quot;|AL| BIG BROTHER VIP 2 4K&quot; tvg-logo=&quot;&quot; g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TV1() As String
            Get
                Return ResourceManager.GetString("TV1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
